/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package metodoburbuja;

import com.jtattoo.plaf.acryl.AcrylLookAndFeel;
import com.jtattoo.plaf.aero.AeroLookAndFeel;
import com.jtattoo.plaf.aluminium.AluminiumLookAndFeel;
import com.jtattoo.plaf.bernstein.BernsteinLookAndFeel;
import com.jtattoo.plaf.fast.FastLookAndFeel;
import com.jtattoo.plaf.graphite.GraphiteLookAndFeel;
import com.jtattoo.plaf.hifi.HiFiLookAndFeel;
import com.jtattoo.plaf.luna.LunaLookAndFeel;
import com.jtattoo.plaf.mcwin.McWinLookAndFeel;
import com.jtattoo.plaf.mint.MintLookAndFeel;
import com.jtattoo.plaf.noire.NoireLookAndFeel;
import com.jtattoo.plaf.smart.SmartLookAndFeel;
import com.jtattoo.plaf.texture.TextureLookAndFeel;
import com.sun.java.swing.plaf.motif.MotifLookAndFeel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.LookAndFeel;
import javax.swing.plaf.basic.BasicLookAndFeel;
import javax.swing.plaf.metal.MetalLookAndFeel;
import javax.swing.plaf.multi.MultiLookAndFeel;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;
import javax.swing.plaf.synth.SynthLookAndFeel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luisg
 */
public class Frame extends javax.swing.JFrame {

    MetodoBurbuja burbuja = new MetodoBurbuja();
    DefaultTableModel modelo;
    int numeros[];
    int cantidad;
    /**
     * Creates new form BurbujaPrueba
     */
    public Frame() {
        initComponents();
        setLocationRelativeTo(null);
        modelo = (DefaultTableModel) jTable1.getModel();
        limpiarJTable();
        btnLimpiador.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnPedirNumeros = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnMayorMenor = new javax.swing.JButton();
        btnMenorAMayor = new javax.swing.JButton();
        btnLimpiador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        BtnPedirNumeros.setText("Pedir Numeros");
        BtnPedirNumeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPedirNumerosActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnMayorMenor.setText("Mayor a Menor");
        btnMayorMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMayorMenorActionPerformed(evt);
            }
        });

        btnMenorAMayor.setText("Menor a Mayor");
        btnMenorAMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenorAMayorActionPerformed(evt);
            }
        });

        btnLimpiador.setText("Limpiar Tabla");
        btnLimpiador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(BtnPedirNumeros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMayorMenor)
                .addGap(136, 136, 136)
                .addComponent(btnMenorAMayor)
                .addGap(96, 96, 96))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(btnLimpiador)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnPedirNumeros)
                    .addComponent(btnMayorMenor)
                    .addComponent(btnMenorAMayor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiador)
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnPedirNumerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPedirNumerosActionPerformed
        // TODO add your handling code here:
        limpiarJTable();
        cantidad = Integer.parseInt(JOptionPane.showInputDialog("dame la cantidad de numeros a ordenar.."));
        numeros = burbuja.pedirNumeros(numeros, cantidad);
        Object titulos[] = new Object[numeros.length+1];
        titulos[0]= "<html>columnas <br> filas </html> ";
        Object contenido[] = new Object[numeros.length+1];
        contenido[0]= 1;
        if (numeros != null) {
            for (int i = 0; i < numeros.length; i++) {
                titulos[i+1] = "" + (i + 1);
                contenido[i+1] = numeros[i];
            }
        }

        modelo.setColumnIdentifiers(titulos);
        modelo.addRow(contenido);
        btnMayorMenor.setEnabled(true);
        btnMenorAMayor.setEnabled(true);
    }//GEN-LAST:event_BtnPedirNumerosActionPerformed

    private void btnMayorMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMayorMenorActionPerformed
        try {
            // TODO add your handling code here:
            MetodoBurbuja.OrdenaMayorMenor(numeros, jTable1);
            btnMayorMenor.setEnabled(false);
            btnMenorAMayor.setEnabled(false);
            BtnPedirNumeros.setEnabled(false);
            btnLimpiador.setEnabled(true);
        } catch (InterruptedException ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMayorMenorActionPerformed

    private void btnMenorAMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenorAMayorActionPerformed
        // TODO add your handling code here:
        try {
            burbuja.OrdenaMenorMayor(numeros, jTable1);
            btnMayorMenor.setEnabled(false);
            btnMenorAMayor.setEnabled(false);
            BtnPedirNumeros.setEnabled(false);
            btnLimpiador.setEnabled(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnMenorAMayorActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        btnMayorMenor.setEnabled(false);
        btnMenorAMayor.setEnabled(false);
        
    }//GEN-LAST:event_formWindowOpened

    private void btnLimpiadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiadorActionPerformed
        // TODO add your handling code here:
        limpiarJTable2();
        BtnPedirNumeros.setEnabled(true);
        btnMayorMenor.setEnabled(true);
        btnMenorAMayor.setEnabled(true);
        btnLimpiador.setEnabled(false);
    }//GEN-LAST:event_btnLimpiadorActionPerformed
    // limpia todas las filas de la tabla
    public void limpiarJTable() {
        for (int i = modelo.getRowCount() - 1; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }
    
    // deja solo la primer fila de la tabla
    public void limpiarJTable2() {
        for (int i = modelo.getRowCount() - 1; i >= 1; i--) {
            modelo.removeRow(i);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            
            //javax.swing.UIManager.setLookAndFeel(new AcrylLookAndFeel());
            //javax.swing.UIManager.setLookAndFeel(new AeroLookAndFeel());
            //javax.swing.UIManager.setLookAndFeel(new AluminiumLookAndFeel());
            //javax.swing.UIManager.setLookAndFeel(new BernsteinLookAndFeel());
            //javax.swing.UIManager.setLookAndFeel(new FastLookAndFeel());
            //***************************
            //javax.swing.UIManager.setLookAndFeel(new GraphiteLookAndFeel());
            javax.swing.UIManager.setLookAndFeel(new HiFiLookAndFeel());
            //***********
            //javax.swing.UIManager.setLookAndFeel(new LunaLookAndFeel());
            //*****
            //javax.swing.UIManager.setLookAndFeel(new McWinLookAndFeel());
            //*****
            //javax.swing.UIManager.setLookAndFeel(new MetalLookAndFeel());
            //javax.swing.UIManager.setLookAndFeel(new MintLookAndFeel());
            //javax.swing.UIManager.setLookAndFeel(new MotifLookAndFeel());
            //javax.swing.UIManager.setLookAndFeel(new NimbusLookAndFeel());
            //********
            //javax.swing.UIManager.setLookAndFeel(new NoireLookAndFeel());
            //******
            //javax.swing.UIManager.setLookAndFeel(new SmartLookAndFeel());
            //javax.swing.UIManager.setLookAndFeel(new TextureLookAndFeel());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        
        //</editor-fold>
        /*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        */
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnPedirNumeros;
    private javax.swing.JButton btnLimpiador;
    private javax.swing.JButton btnMayorMenor;
    private javax.swing.JButton btnMenorAMayor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
